// client/src/pages/manage/index.tsx
import './index.less';
import { remote, ipcRenderer } from 'electron';
import TypeWeibo from '@/../../src/type/namespace/weibo';
import { useState, useEffect } from 'react';
import { enableMapSet } from 'immer';
enableMapSet();
import produce from 'immer';
import { Table, Card, Select, Button } from 'antd';
import Util from '@/library/util';
import moment from 'moment';
import path from 'path';

let Option = Select.Option;
let MUser = remote.getGlobal('mUser');
let MBlog = remote.getGlobal('mBlog');

type BlogDistributionItem = {
  date: string;
  key: string;
  type: 'year' | 'month' | 'day';
  startAt: number;
  count: number;
  childrenMap: BlogDistributionObj;
};

type BlogDistributionObj = { [key: string]: BlogDistributionItem };

const Const_Default_Storage_Select: {
  year: string;
  month: string;
  day: string;
  yearList: string[];
  monthList: string[];
  blogList: TypeWeibo.TypeMblog[];
} = {
  year: '',
  month: '',
  day: '',
  yearList: [],
  monthList: [],
  blogList: [],
};

export default function IndexPage() {
  let [$$userDatabase, set$$UserDatabase] = useState<
    Map<string, TypeWeibo.TypeWeiboUserInfo>
  >(produce(new Map(), (raw) => raw));
  let [
    blogDistributionObj,
    setBlogDistributionObj,
  ] = useState<BlogDistributionObj>({});

  let [isLoading, setIsLoading] = useState<boolean>(false);
  let [selectUserId, setSelectUserId] = useState<string>('');
  let [selectWeiboListPageNo, setSelectWeiboListPageNo] = useState<number>(1);
  let [selectDateListPageNo, setSelectDateListPageNo] = useState<number>(1);

  let [$$storageSelect, set$$StorageSelect] = useState<{
    year: string;
    month: string;
    day: string;
    yearList: string[];
    monthList: string[];
    blogList: TypeWeibo.TypeMblog[];
  }>(produce(Const_Default_Storage_Select, (raw) => raw));

  /**
   * 获取用户信息列表
   */
  async function asyncFetchUserInfoList() {
    let userInfoList: TypeWeibo.TypeWeiboUserInfo[] = await MUser.asyncGetUserList();
    for (let record of userInfoList) {
      set$$UserDatabase(($$oldDatabase) => {
        return produce($$oldDatabase, (raw) => {
          raw.set(`${record.id}`, record);
        });
      });
    }
  }
  async function asyncGetDistribute() {
    setIsLoading(true);
    // console.log('start to load distributionMap');
    let distributionObj: BlogDistributionObj = await MBlog.asyncGetWeiboDistribution(
      selectUserId,
    );
    // distributionObj.forEach((item) => console.log(item));
    setIsLoading(false);
    setBlogDistributionObj(distributionObj);

    set$$StorageSelect(
      produce(Const_Default_Storage_Select, (raw) => {
        raw.yearList = Object.keys(distributionObj);
      }),
    );
  }

  /**
   * 获取当天微博数据列表
   */
  async function asyncGetBlogListInRange(startAt: number, endAt: number) {
    let blogList = (await MBlog.asyncGetMblogList(
      selectUserId,
      startAt,
      endAt,
    )) as TypeWeibo.TypeMblog[];
    return blogList;
  }

  // 支持点选
  async function asyncHandleStorageSelectInTable(
    selectDate: string,
    type: 'year' | 'month' | 'day',
  ) {
    if (type === 'year') {
      let rowItem = blogDistributionObj[selectDate];

      set$$StorageSelect(($$storageSelect) => {
        return produce($$storageSelect, (raw) => {
          raw.year = rowItem.date;
          let rawMonthItemList: BlogDistributionItem[] = [];
          for (let key of Object.keys(rowItem.childrenMap)) {
            rawMonthItemList.push(rowItem.childrenMap[key]);
          }
          rawMonthItemList.sort(
            (a: BlogDistributionItem, b: BlogDistributionItem) => {
              // 从object中取出的数据顺序是乱的, 手工排序一下
              return a.startAt - b.startAt;
            },
          );
          raw.monthList = rawMonthItemList.map((item) => item.date);
          raw.month = '';
          raw.blogList = [];
        });
      });
    }
    if (type === 'month') {
      let rowItem =
        blogDistributionObj[$$storageSelect.year].childrenMap[selectDate];

      set$$StorageSelect(($$storageSelect) => {
        return produce($$storageSelect, (raw) => {
          raw.month = rowItem.date;
          raw.blogList = [];
        });
      });
    }
    if (type === 'day') {
      let row =
        blogDistributionObj[$$storageSelect.year].childrenMap[
          $$storageSelect.month
        ].childrenMap[selectDate];

      let startAt = row.startAt;
      let endAt = row.startAt + 86400 - 1;
      let blogList = await asyncGetBlogListInRange(startAt, endAt);
      set$$StorageSelect(($$storageSelect) => {
        return produce($$storageSelect, (raw) => {
          raw.day = row.date;
          raw.blogList = blogList;
        });
      });
    }
  }

  /**
   * 重置选择
   */
  function resetSelect() {
    setSelectDateListPageNo(1);
    setSelectWeiboListPageNo(1);
    set$$StorageSelect(() => {
      return produce(Const_Default_Storage_Select, (raw) => raw);
    });
  }

  /**
   * 重置选择数据
   */
  async function asyncRefreshData() {
    set$$UserDatabase(produce(new Map(), (raw) => raw));
    setBlogDistributionObj({});
    set$$StorageSelect(produce(Const_Default_Storage_Select, (raw) => raw));
    setSelectUserId('');
    setSelectDateListPageNo(1);
    setSelectWeiboListPageNo(1);
    setIsLoading(false);
    await asyncFetchUserInfoList();
  }

  /**
   * 导出数据
   */
  async function asyncDataTransferExport(config: {
    screen_name: string;
    exportUri: string;
    uid: string;
    exportStartAt: number;
    exportEndAt: number;
  }) {
    let saveUri = await remote.dialog.showSaveDialogSync({
      title: '文件保存地址',
      filters: [
        {
          // name: `稳部落导出的用户_${config.screen_name}_微博记录`,
          name: ``,
          extensions: ['json'],
        },
      ],
    });
    if (!config.uid || !saveUri) {
      // 没有uid, 无法导出
      return;
    }
    let finalConfig = {
      uid: config.uid,
      exportStartAt: config.exportStartAt,
      exportEndAt: config.exportEndAt,
      exportUri: path.resolve(saveUri),
    };

    console.log('config => ', finalConfig);

    ipcRenderer.sendSync('dataTransferExport', finalConfig);
  }

  useEffect(() => {
    asyncFetchUserInfoList();
  }, []);

  useEffect(() => {
    if ($$userDatabase.has(selectUserId)) {
      asyncGetDistribute();
      resetSelect();
    }
  }, [selectUserId]);

  let userInfoList: TypeWeibo.TypeWeiboUserInfo[] = [];
  for (let key of $$userDatabase.keys()) {
    let record = $$userDatabase.get(key);
    userInfoList.push({
      ...record,
      key: `${key}`,
    });
  }

  let currentUserInfo = $$userDatabase.get(selectUserId);

  let yearOptionEleList = $$storageSelect.yearList.map((item, index) => {
    return (
      <Option value={item} key={index}>
        {item}
      </Option>
    );
  });
  let yearSelectEle = (
    <Select
      className="year-select"
      value={$$storageSelect.year}
      onSelect={(selectDate: string) => {
        asyncHandleStorageSelectInTable(selectDate, 'year');
      }}
    >
      {yearOptionEleList}
    </Select>
  );
  let monthOptionEleList = $$storageSelect.monthList.map((item, index) => {
    return (
      <Option value={item} key={index}>
        {item}
      </Option>
    );
  });
  let monthSelectEle = (
    <Select
      className="month-select"
      value={$$storageSelect.month}
      onSelect={(selectDate: string) => {
        asyncHandleStorageSelectInTable(selectDate, 'month');
      }}
    >
      {monthOptionEleList}
    </Select>
  );

  // console.log('blogDistributionObj => ', blogDistributionObj);

  function getSummaryList() {
    if (Object.keys(blogDistributionObj).length === 0) {
      return [];
    }
    const { year, month } = $$storageSelect;
    // console.log(`refresh data => ${year} ${month}`, $$storageSelect);
    let summaryList: BlogDistributionItem[] = [];
    if (year === '') {
      // 按年展示
      Object.keys(blogDistributionObj).forEach((year_str) => {
        let item = blogDistributionObj[year_str];
        summaryList.push({
          ...item,
          key: `${item.date}`,
        });
      });
      return summaryList;
    }
    if (month === '') {
      // 按月展示
      let yearDistributionObj = blogDistributionObj[year]['childrenMap'];
      Object.keys(yearDistributionObj).forEach((month_str) => {
        let item = yearDistributionObj[month_str];
        summaryList.push({
          ...item,
          key: `${item.date}`,
        });
      });
      return summaryList;
    }
    // 按天展示
    let monthDistributionObj =
      blogDistributionObj[year]['childrenMap'][month]['childrenMap'];
    Object.keys(monthDistributionObj).forEach((day_str) => {
      let item = monthDistributionObj[day_str];
      summaryList.push({
        ...item,
        key: `${item.date}`,
      });
    });
    return summaryList;
  }

  let rawSummaryList = getSummaryList();
  rawSummaryList.sort((a, b) => {
    // 从object中取出的数据顺序是乱的, 手工排序一下
    return a.startAt - b.startAt;
  });
  let weiboStorageSummaryList = rawSummaryList;
  // console.log('weiboStorageSummaryList => ', weiboStorageSummaryList);

  let blogListEle = null;
  if ($$storageSelect.blogList.length > 0) {
    // console.log('$$storageSelect.blogList => ', $$storageSelect.blogList);
    blogListEle = (
      <Card
        title={`${$$userDatabase.get(selectUserId)?.screen_name} 在${
          $$storageSelect.year
        }${$$storageSelect.month}${$$storageSelect.day}发布的微博列表`}
      >
        <Table
          pagination={{
            onChange: (page) => {
              setSelectWeiboListPageNo(page);
            },
            current: selectWeiboListPageNo,
          }}
          dataSource={$$storageSelect.blogList}
          rowKey={(item) => item.id}
          columns={[
            {
              title: '发布时间',
              width: '120px',
              render: (record) => {
                return (
                  <span title={'微博id:' + record.id} key={record.id}>
                    {moment
                      .unix(record.created_timestamp_at)
                      .format('YYYY-MM-DD HH:mm:ss')}
                  </span>
                );
              },
            },
            {
              title: '发布内容',
              render: (record: TypeWeibo.TypeMblog) => {
                let picEleList = [];
                let picList = record?.pics || [];
                for (let picItem of picList) {
                  picEleList.push(<img key={picItem.pid} src={picItem.url} />);
                }
                let retweetedEle = null;
                if (record.retweeted_status) {
                  let picEleList = [];
                  let picList = record?.retweeted_status?.pics || [];
                  for (let picItem of picList) {
                    picEleList.push(
                      <img key={picItem.pid} src={picItem.url} />,
                    );
                  }
                  retweetedEle = (
                    <div
                      className="weibo-repost-item"
                      v-if="scope.row.retweeted_status"
                    >
                      <hr />
                      <div
                        className="weibo-text"
                        dangerouslySetInnerHTML={{
                          __html:
                            record.retweeted_status.raw_text ||
                            record.retweeted_status.text,
                        }}
                      />
                      <div className="weibo-img-list">{picEleList}</div>
                    </div>
                  );
                }

                return (
                  <div className="weibo" key={record.id}>
                    <div className="weibo-raw-item">
                      <div
                        className="weibo-text"
                        dangerouslySetInnerHTML={{
                          __html: record.raw_text || record.text,
                        }}
                      />
                      <div className="weibo-img-list">
                        <div>{picEleList}</div>
                      </div>
                      {retweetedEle}
                    </div>
                  </div>
                );
              },
            },
          ]}
        ></Table>
      </Card>
    );
  }

  let uid = selectUserId;
  let exportUri = '';

  let exportStartAt = moment('2009-01-01 00:00:00').unix();
  let exportEndAt = moment().unix();
  if ($$storageSelect.year) {
    if ($$storageSelect.month) {
      exportStartAt = moment(
        `${$$storageSelect.year}-${$$storageSelect.month}`,
        'YYYY年-MM月',
      )
        .startOf('month')
        .unix();
      exportEndAt = moment(
        `${$$storageSelect.year}-${$$storageSelect.month}`,
        'YYYY年-MM月',
      )
        .endOf('month')
        .unix();
    } else {
      exportStartAt = moment($$storageSelect.year, 'YYYY年')
        .startOf('year')
        .unix();
      exportEndAt = moment($$storageSelect.year, 'YYYY年').endOf('year').unix();
    }
  }

  let exportTip = `导出微博记录`;
  if (currentUserInfo?.screen_name) {
    if ($$storageSelect.year) {
      if ($$storageSelect.month) {
        exportTip = `导出${currentUserInfo?.screen_name}在${$$storageSelect.year}-${$$storageSelect.month}的所有微博记录`;
      } else {
        exportTip = `导出${currentUserInfo?.screen_name}在${$$storageSelect.year}的所有微博记录`;
      }
    } else {
      exportTip = `导出${currentUserInfo?.screen_name}的所有微博记录`;
    }
  }

  // 生成导出配置
  let exportConfig = {
    screen_name: currentUserInfo?.screen_name || '',
    exportUri,
    uid,
    exportStartAt: exportStartAt,
    exportEndAt: exportEndAt,
  };

  return (
    <div className="manager-container">
      <Card title="Card title">
        <Table
          onRow={(record) => {
            return {
              onClick: () => {
                setSelectUserId(`${record.id}`);
              },
            };
          }}
          rowSelection={{
            selectedRowKeys: [selectUserId],
            type: 'radio',
          }}
          rowKey={(item) => item.id}
          columns={[
            {
              title: '已缓存账号',
              dataIndex: 'screen_name',
              render: (text, record: TypeWeibo.TypeWeiboUserInfo, index) => {
                return (
                  <div className="user-info" key={record.id}>
                    <img
                      alt={record.screen_name}
                      src={record.avatar_hd}
                      className="avatar"
                    />
                    <div className="name">{record.screen_name}</div>
                    <div className="id">({record.id})</div>
                  </div>
                );
              },
            },
            {
              title: '个人简介',
              dataIndex: 'description',
              key: 'description',
            },
          ]}
          dataSource={userInfoList}
          pagination={false}
        ></Table>
      </Card>
      <Card
        title={
          currentUserInfo?.screen_name
            ? `${currentUserInfo?.screen_name} 已完成备份的微博列表`
            : ''
        }
      >
        {yearSelectEle}
        &nbsp;
        {monthSelectEle}
        &nbsp;
        <Button
          type="default"
          disabled={selectUserId === ''}
          onClick={() => {
            asyncDataTransferExport(exportConfig);
          }}
        >
          {exportTip}
        </Button>
        &nbsp;
        <Button
          type="default"
          onClick={() => {
            resetSelect();
          }}
        >
          重选
        </Button>
        &nbsp;
        <Button
          type="primary"
          onClick={() => {
            asyncRefreshData();
          }}
        >
          刷新数据
        </Button>
        &nbsp;
        <Table
          pagination={{
            onChange: (page) => {
              setSelectDateListPageNo(page);
            },
            current: selectDateListPageNo,
          }}
          loading={isLoading}
          rowSelection={{
            selectedRowKeys: [$$storageSelect.day],
            type: 'radio',
          }}
          dataSource={weiboStorageSummaryList}
          columns={[
            {
              title: '日期',
              dataIndex: 'date',
              key: 'date',
            },
            {
              title: '微博数量',
              dataIndex: 'count',
              key: 'count',
            },
          ]}
          onRow={(record, index) => {
            return {
              onClick: () => {
                let selectType = record.type;
                switch (selectType) {
                  case 'year':
                    asyncHandleStorageSelectInTable(record.date, 'year');
                    break;
                  case 'month':
                    asyncHandleStorageSelectInTable(record.date, 'month');
                    break;
                  case 'day':
                    asyncHandleStorageSelectInTable(record.date, 'day');
                    break;
                }

                // console.log(`click ${index} => `, record);
              },
            };
          }}
        ></Table>
      </Card>
      {blogListEle}
    </div>
  );
}

// visible: (...)
// created_at: (...)
// id: (...)
// mid: (...)
// can_edit: (...)
// show_additional_indication: (...)
// text: (...)
// source: (...)
// favorited: (...)
// pic_ids: (...)
// pic_types: (...)
// is_paid: (...)
// mblog_vip_type: (...)
// user: (...)
// pid: (...)
// pidstr: (...)
// retweeted_status: (...)
// reposts_count: (...)
// comments_count: (...)
// attitudes_count: (...)
// pending_approval_count: (...)
// isLongText: (...)
// reward_exhibition_type: (...)
// hide_flag: (...)
// mlevel: (...)
// darwin_tags: (...)
// mblogtype: (...)
// rid: (...)
// more_info_type: (...)
// extern_safe: (...)
// number_display_strategy: (...)
// enable_comment_guide: (...)
// content_auth: (...)
// pic_num: (...)
// alchemy_params: (...)
// mblog_menu_new_style: (...)
// reads_count: (...)
// title: (...)
// raw_text: (...)
// bid: (...)
// created_timestamp_at: (...)

// gui/src/view/manage/index.vue
<template>
  <div class="mamage-tab">
    <el-table :data="userList" style="width: 100%" highlight-current-row @current-change="handleSelectChange">
      <el-table-column type="index" />
      <el-table-column label="已缓存账号">
        <template slot-scope="scope">
          <div class="user-info">
            <img :alt="scope.row.screen_name" :src="scope.row.avatar_hd" class="avatar" />
            <div class="name">{{ scope.row.screen_name }}</div>
            <div class="id">({{ scope.row.id }})</div>
          </div>
        </template>
      </el-table-column>
      <el-table-column prop="description" label="个人简介"></el-table-column>
    </el-table>

    <el-card class="box-card" shadow="hover" v-loading="state.loading.distribution">
      <div slot="header" class="clearfix">
        <span>{{ currentSelectUser['screen_name'] }} 微博缓存情况</span>
      </div>
      <el-select v-model="state.storageSelect.year" placeholder="年">
        <el-option
          v-for="(yearItem, index) in state.storageSelect.yearList"
          :key="index"
          :label="yearItem"
          :value="yearItem"
        ></el-option>
      </el-select>
      <el-select v-model="state.storageSelect.month" placeholder="月">
        <el-option
          v-for="(monthItem, index) in state.storageSelect.monthList"
          :key="index"
          :label="monthItem"
          :value="monthItem"
        ></el-option>
      </el-select>
      <el-button @click="clearStorageSelect" type="success">重选</el-button>
      <el-button @click="refresh" type="primary">刷新数据</el-button>
      <el-table
        v-on:row-click="handleStorageSelectInTable"
        :data="weiboStorageSummaryList"
        style="width: 100%;margin-bottom: 20px;"
        border
        highlight-current-row
        show-summary
      >
        <el-table-column prop="date" label="时间" width="180"></el-table-column>
        <el-table-column prop="count" label="缓存微博数"></el-table-column>
      </el-table>
    </el-card>
    <el-card class="box-card" shadow="hover" v-if="state.storageSelect.day">
      <div slot="header" class="clearfix">
        <span
          >{{ currentSelectUser['screen_name'] }} 在{{ state.storageSelect.year }}{{ state.storageSelect.month
          }}{{ state.storageSelect.day }}发布的微博列表</span
        >
      </div>
      <el-table :data="state.storageSelect.blogList" border cell-class-name="mblog-detail-list-cell">
        <el-table-column prop="id" label="id" width="180"></el-table-column>
        <el-table-column label="发布时间" width="180">
          <template slot-scope="scope">
            <div>{{ formatUnix(scope.row.created_timestamp_at) }}</div>
          </template>
        </el-table-column>
        <el-table-column label="微博内容">
          <template slot-scope="scope">
            <div class="weibo">
              <div class="weibo-raw-item">
                <div class="weibo-text" v-html="scope.row.raw_text || scope.row.text" />
                <div class="weibo-img-list">
                  <div v-for="pic in scope.row.pics">
                    <img :src="pic.url" />
                  </div>
                </div>
                <div class="weibo-repost-item" v-if="scope.row.retweeted_status">
                  <hr />
                  <div
                    class="weibo-text"
                    v-html="scope.row.retweeted_status.raw_text || scope.row.retweeted_status.text"
                  />
                  <div class="weibo-img-list">
                    <div v-for="retweetedPic in scope.row.retweeted_status.pics">
                      <img :src="retweetedPic.url" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </template>
        </el-table-column>
      </el-table>
    </el-card>
  </div>
</template>

<script lang="ts">
import { remote } from 'electron'
import Vue from 'vue'
import _ from 'lodash'
import moment from 'moment'
import TypeWeibo from '~/gui/../src/type/namespace/weibo'

type BlogDistributionItem = {
  date: string
  key: string
  type: 'year' | 'month' | 'day'
  startAt: number
  count: number
  childrenMap: BlogDistributionMap
}

type BlogDistributionMap = Map<
  string,
  {
    date: string
    key: string
    type: 'year' | 'month' | 'day'
    startAt: number
    count: number
    childrenMap: BlogDistributionMap
  }
>

export default {
  name: 'manage',
  data: function(): {
    database: {
      userMap: Map<string, TypeWeibo.TypeWeiboUserInfo>
      blogDistributionMap: BlogDistributionMap
    }
    state: {
      selectUserId: string
      storageSelect: {
        year: string
        month: string
        day: string
        yearList: string[]
        monthList: string[]
        blogList: TypeWeibo.TypeMblog[]
      }
      loading: {
        distribution: boolean
      }
    }
    forceUpdate: number
  } {
    return {
      database: {
        userMap: new Map(),
        blogDistributionMap: new Map(),
      },
      state: {
        selectUserId: '',
        storageSelect: {
          year: '',
          month: '',
          day: '',
          yearList: [],
          monthList: [],
          blogList: [],
        },
        loading: {
          distribution: false,
        },
      },
      forceUpdate: 0,
    }
  },

  methods: {
    async getUserList() {
      let MUser = remote.getGlobal('mUser')
      let recordList = (await MUser.asyncGetUserList()) as TypeWeibo.TypeWeiboUserInfo[]
      let userMap = new Map()
      for (let record of recordList) {
        userMap.set(record.id, record)
      }
      this.database.userMap = userMap
      this.database.blogDistributionMap = new Map()
    },
    async getDistribute() {
      let MBlog = remote.getGlobal('mBlog')
      this.state.loading.distribution = true
      let distributionMap = (await MBlog.asyncGetWeiboDistribution(this.state.selectUserId)) as BlogDistributionMap
      this.state.loading.distribution = false
      console.log('distribution => ', distributionMap)
      // 必须要手工转成obj
      this.database.blogDistributionMap = distributionMap
      this.forceUpdate++
    },
    /**
     * 获取当天微博数据列表
     */
    async getBlogListInRange(startAt: number, endAt: number) {
      let MBlog = remote.getGlobal('mBlog')
      let blogList = (await MBlog.asyncGetMblogList(this.state.selectUserId, startAt, endAt)) as TypeWeibo.TypeMblog[]
      console.log(JSON.parse(JSON.stringify(blogList)))
      return blogList
    },
    async handleSelectChange(currentRow: TypeWeibo.TypeWeiboUserInfo, oldCurrentRow: TypeWeibo.TypeWeiboUserInfo) {
      this.state.selectUserId = `${currentRow.id}`
      this.resetSelect()
      await this.getDistribute()
    },
    // 支持点选
    async handleStorageSelectInTable(row: BlogDistributionItem) {
      if (row.type === 'year') {
        this.state.storageSelect.year = row.date
        this.state.storageSelect.blogList = []
      }
      if (row.type === 'month') {
        this.state.storageSelect.month = row.date
        this.state.storageSelect.blogList = []
      }
      if (row.type === 'day') {
        this.state.storageSelect.day = row.date
        let startAt = row.startAt
        let endAt = row.startAt + 86400 - 1
        let blogList = await this.getBlogListInRange(startAt, endAt)
        this.state.storageSelect.blogList = blogList
      }
    },
    weiboStorageYearList() {
      if (this.database.blogDistributionMap.size === 0) {
        return []
      }
      // 年列表
      let yearList: string[] = []
      this.database.blogDistributionMap.forEach(item => {
        yearList.push(item.date)
        console.log('yearList push')
      })

      console.log('dasdas =>', this.database.blogDistributionMap)
      console.log('yearList =>', this.forceUpdate)
      console.log('yearList =>', yearList)
      return yearList
    },
    weiboStorageMonthList() {
      if (
        this.state.storageSelect.year === '' &&
        !this.database.blogDistributionMap.get(this.state.storageSelect.year)
      ) {
        return []
      }
      // 月列表
      let monthList: string[] = []
      let selectMonthMap = this.database.blogDistributionMap.get(this.state.storageSelect.year)['childrenMap']
      selectMonthMap.forEach(item => {
        console.log('monthList push')
        monthList.push(item.date)
      })
      console.log('monthList =>', this.forceUpdate)
      console.log('monthList =>', monthList)
      return monthList
    },
    async loadData() {
      await this.getUserList()
      if (this.userList.length > 0) {
        this.state.selectUserId = `${this.userList[0].id}`
      }
    },
    async refresh() {
      this.resetSelect()
      await this.loadData()
    },
    clearStorageSelect() {
      this.state.storageSelect.year = ''
      this.state.storageSelect.month = ''
      this.state.storageSelect.day = ''
      this.state.storageSelect.blogList = []
    },
    resetSelect() {
      this.state.storageSelect.month = ''
      this.state.storageSelect.year = ''
      this.state.storageSelect.day = ''
      this.state.storageSelect.yearList = []
      this.state.storageSelect.monthList = []
      this.state.storageSelect.blogList = []
    },
    formatUnix(timestamp: number) {
      return moment.unix(timestamp).format('YYYY-MM-DD HH:mm:ss')
    },
  },
  computed: {
    userList(): TypeWeibo.TypeWeiboUserInfo[] {
      let list = []
      let int = this.database.userMap.values()
      for (let item of int) {
        list.push(item)
      }
      console.log('list =>', list)
      return list
    },
    currentSelectUser() {
      if (this.state.selectUserId) {
        let uidStr = `${this.state.selectUserId}`
        let uidInt = parseInt(uidStr, 10)
        return this.database.userMap.get(uidStr) || this.database.userMap.get(uidInt) || {}
      } else {
        return {}
      }
    },
    weiboStorageSummaryList() {
      if (this.database.blogDistributionMap.size === 0) {
        return []
      }
      const { year, month } = this.state.storageSelect
      const blogDistributionMap = this.database.blogDistributionMap
      let summaryList = []
      if (year === '') {
        // 按年展示
        blogDistributionMap.forEach(item => {
          summaryList.push(item)
        })
        return summaryList
      }
      if (month === '') {
        // 按月展示
        let yearDistributionMap = blogDistributionMap.get(year)['childrenMap']
        yearDistributionMap.forEach(item => {
          summaryList.push(item)
        })
        return summaryList
      }
      // 按天展示
      let monthDistributionMap = blogDistributionMap.get(year)!['childrenMap'].get(month)!['childrenMap']
      monthDistributionMap.forEach(item => {
        summaryList.push(item)
      })
      return summaryList
    },
  },
  watch: {
    forceUpdate() {
      this.state.storageSelect.yearList = this.weiboStorageYearList()
    },
    ['state.storageSelect.year']: function() {
      this.state.storageSelect.month = ''
      this.state.storageSelect.monthList = this.weiboStorageMonthList()
    },
  },
  async mounted() {
    // 初始化时自动载入数据
    await this.loadData()
  },
}
</script>

<style lang="less">
.mamage-tab {
  .user-info {
    display: flex;
    font-size: 16px;
    align-items: center;
    img.avatar {
      width: 30px;
      height: 30px;
      border-radius: 30px;
      margin-right: 16px;
    }
  }
  .mblog-detail-list-cell {
    // 所有元素顶部对齐
    vertical-align: top;
  }
}
</style>
